server:
  port: 8080    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。
#  ssl:
#    key-store-password: iinn49ui    #填写jks-password.txt文件内的密码。
#    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
#    key-store: classpath:chinese.redamancyxun.fun.jks   #您需要使用实际的证书名称替换domain_name.jks。
  tomcat:
    uriEncoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  #?????????QQ?????????
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com #???QQ?????????? SMTP ?????, ????, ???????????, ??(????, ????)???: smtp.xxx.com?????
    port: 587
    username: 2044978721@qq.com #qq??
    password: pajdcdkinctsbchd #qq?????
    protocol: smtp #??????
    properties.mail.smtp.auth: true   #????????????true,?????????????
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: false #??SSL ???????
    default-encoding: utf-8
  datasource:
    url: jdbc:mysql://121.43.62.35:3306/eq_master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a13738780767
  jackson:
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      database: 0
      host: 121.43.62.35
      port: 6379
      timeout: 1000
#    password: fu040913

mybatis-plus:
  global-config:
    db-config:
      #????????NULL??
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true


logback:
  dir: logs
  #????
  filename:
    all: springboot-base-frame-all
    info: springboot-base-frame-info
    warn: springboot-base-frame-warn
    error: springboot-base-frame-error
  #???????
  maxhistory: 10
  #?????????
  maxfilesize: 100MB
  #????
  level: debug
  #??????
  charset: UTF-8
  #????
  CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} %boldYellow([%thread]) %highlight(%-5level) %boldGreen(%logger{50}) - %msg%n'
  FILE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
#
#uniapp:
#  appid: wxa70d503b20ed975b #??????????????appid????????
#  appsecret: fad288a10751b57c04d064a0f2e1edac #??????????????appsecret????????